ALTER TABLE dummy
    ADD name VARCHAR(255) NULL;

# ALTER TABLE jt_user
#     MODIFY id BIGINT AUTO_INCREMENT;
#
# ALTER TABLE mp_instructor
#     MODIFY id BIGINT AUTO_INCREMENT;
#
# ALTER TABLE mp_mentor
#     MODIFY id BIGINT AUTO_INCREMENT;
#
# ALTER TABLE mp_ta
#     MODIFY id BIGINT AUTO_INCREMENT;
#
# ALTER TABLE st_user
#     MODIFY id BIGINT AUTO_INCREMENT;